<?php
/*
* @category  Theme
* @package   Bestresponse
* @author    Best Response Media Developers <dev@bestresponsemedia.co.uk>
* @copyright 2019 Best Response Media (http://bestresponsemedia.co.uk/)
* @license   Best Response Media Licence http://bestresponsemedia.co.uk/license/
* @link      http://bestresponsemedia.co.uk/
* ┌─┐┌─┐┌─┐┌┬┐ ┬─┐┌─┐┌─┐┌─┐┌─┐┌┐┬┌─┐┌─┐ ┌┐┌┐┌─┐┌─┐┬┌─┐
* │─│├┤ └─┐ │  ├┬┘├┤ └─┐├─┘│ ││││└─┐├┤  ││││├┤ │ │││─│
* └─┘└─┘└─┘ ┴  ┴└─└─┘└─┘┴  └─┘┴└┘└─┘└─┘ ┴└┘┴└─┘└─┘┴┴ ┴
*/
?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Magento\Search\Helper\Data */
$helper = $this->helper(\Magento\Search\Helper\Data::class);
?>
<div id="header-search" class="header-search">
  <div class="block-content">
    <form class="form minisearch" id="search_mini_form" action="<?= /* @escapeNotVerified */ $helper->getResultUrl() ?>" method="get">
      
      <div class="field search">
        <label class="label" for="search" data-role="minisearch-label">
          <span><?= /* @escapeNotVerified */ __('Search') ?></span>
        </label>
        <div class="control">
          <div class="search-icon"></div>
          <input id="search"
            data-mage-init='{"quickSearch":{
                              "formSelector":"#search_mini_form",
                              "url":"<?= /* @escapeNotVerified */ $helper->getSuggestUrl()?>",
                              "destinationSelector":"#search_autocomplete"}
                            }'
            type="text"
            name="<?= /* @escapeNotVerified */ $helper->getQueryParamName() ?>"
            value="<?= /* @escapeNotVerified */ $helper->getEscapedQueryText() ?>"
            placeholder="<?= /* @escapeNotVerified */ __('Search entire store here...') ?>"
            class="input-text"
            maxlength="<?= /* @escapeNotVerified */ $helper->getMaxQueryLength() ?>"
            role="combobox"
            aria-haspopup="false"
            aria-autocomplete="both"
            autocomplete="off"/>
          <div id="search_autocomplete" class="search-autocomplete"></div>
        </div>
      </div>
      <div class="actions">
        <button type="submit"
                title="<?= $block->escapeHtml(__('Search')) ?>"
                class="action search">
           <span><?= /* @escapeNotVerified */ __('Search') ?></span>
        </button>
      </div>
      <div class="search-close"><span></span></div>
    </form>
  </div>
</div>
