<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */
?>
<?php $storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt();?>
<div class="logo">
<?php if ($block->isHomePage()):?>
    <h1>
<?php else: ?>
    <a class="h1" href="<?= $block->getUrl('') ?>" title="<?= /* @escapeNotVerified */ $storeName ?>">
<?php endif ?>
        <img src="<?= /* @escapeNotVerified */ $block->getLogoSrc() ?>"
	         title="<?= $block->escapeHtmlAttr($block->getLogoAlt()) ?>"
	         alt="<?= $block->escapeHtmlAttr($block->getLogoAlt()) ?>"
        />
<?php if ($block->isHomePage()):?>
    </h1>
<?php else:?>
    </a>
<?php endif?>
</div>