<?php
/*
* @category  Theme
* @package   Bestresponse
* @author    Best Response Media Developers <dev@bestresponsemedia.co.uk>
* @copyright 2019 Best Response Media (http://bestresponsemedia.co.uk/)
* @license   Best Response Media Licence http://bestresponsemedia.co.uk/license/
* @link      http://bestresponsemedia.co.uk/
* ┌─┐┌─┐┌─┐┌┬┐ ┬─┐┌─┐┌─┐┌─┐┌─┐┌┐┬┌─┐┌─┐ ┌┐┌┐┌─┐┌─┐┬┌─┐
* │─│├┤ └─┐ │  ├┬┘├┤ └─┐├─┘│ ││││└─┐├┤  ││││├┤ │ │││─│
* └─┘└─┘└─┘ ┴  ┴└─└─┘└─┘┴  └─┘┴└┘└─┘└─┘ ┴└┘┴└─┘└─┘┴┴ ┴
*/
?>
<div class="footer-container">
    <div class="footer">
        <div class="footer-content footer-row">
            <div class="footer-col">
                <div class="h3 toggle-title">Orders</div>
                <ul class="toggle-content">
                    <li><a href="#" title="">Lorem ipsum dolor</a></li>
                    <li><a href="#" title="">consectetur adipisicing elit</a></li>
                    <li><a href="#" title="">Mollitia incidunt tempore eius</a></li>
                    <li><a href="#" title="">voluptatibus animi sed ab</a></li>
                </ul>
            </div>
            <div class="footer-col">
                <div class="h3 toggle-title">Find us</div>
                <ul class="toggle-content">
                    <li><a href="#" title="">Lorem ipsum dolor</a></li>
                    <li><a href="#" title="">consectetur adipisicing elit</a></li>
                    <li><a href="#" title="">Mollitia incidunt tempore eius</a></li>
                    <li><a href="#" title="">voluptatibus animi sed ab</a></li>
                </ul>
            </div>
            <div class="footer-col">
                <div class="h3 toggle-title">About Us</div>
                <ul class="toggle-content">
                    <li><a href="#" title="">Lorem ipsum dolor</a></li>
                    <li><a href="#" title="">consectetur adipisicing elit</a></li>
                    <li><a href="#" title="">Mollitia incidunt tempore eius</a></li>
                    <li><a href="#" title="">voluptatibus animi sed ab</a></li>
                </ul>
            </div>
            <div class="footer-col last">
                <div class="h3 toggle-title">Social</div>
                <ul class="footer-socials toggle-content">
                    <li>
                        <a href="https://twitter.com/" class="icon-twitter"  target="_blank" title="Twitter"></a>
                    </li>
                    <li>
                        <a href="https://www.instagram.com/" class="insta-icon"  target="_blank" title="Instagram"></a>
                    </li>
                    <li>
                        <a href="https://www.facebook.com/" class="icon-facebook"  target="_blank" title="Facebook"></a>
                    </li>
                </ul>

                <?php /*
                <ul class="footer-languages">
                    <form method="get" action="#">
                        <select class="footer-languages-menu" name="footer-languages">
                            <option value="gbp">United kingdom website</option>
                            <option value="us">United states website</option>
                        </select>
                    </form>
                </ul>
                */ ?>
            </div>
        </div>

        <div class="footer-last">
            <div class="footer-row">
                <div class="footer-last-block footer-copyright">
                    <?= $block->getCopyright() ?>
                </div>
                <div class="footer-last-block footer-payments">
                    <img src="<?= $this->getViewFileUrl('images/payments/payments-methods.png'); ?>" alt="Payments" />
                </div>
                <div class="footer-last-block footer-website last">
                    Site by <a href="https://www.bestresponsemedia.co.uk/" target="_blank" title="Best Response Media">Best Response Media.</a>
                </div>
            </div>
        </div>
    </div>
</div>