<?php
/*
* @category  Theme
* @package   Bestresponse
* @author    Best Response Media Developers <dev@bestresponsemedia.co.uk>
* @copyright 2019 Best Response Media (http://bestresponsemedia.co.uk/)
* @license   Best Response Media Licence http://bestresponsemedia.co.uk/license/
* @link      http://bestresponsemedia.co.uk/
* ┌─┐┌─┐┌─┐┌┬┐ ┬─┐┌─┐┌─┐┌─┐┌─┐┌┐┬┌─┐┌─┐ ┌┐┌┐┌─┐┌─┐┬┌─┐
* │─│├┤ └─┐ │  ├┬┘├┤ └─┐├─┘│ ││││└─┐├┤  ││││├┤ │ │││─│
* └─┘└─┘└─┘ ┴  ┴└─└─┘└─┘┴  └─┘┴└┘└─┘└─┘ ┴└┘┴└─┘└─┘┴┴ ┴
*/
?>
<div class="wrapper">
    <div class="slick-slider ">
        <img src="http://www.fickletattoos.com/media/pixelslider/slides/lucky-rabbitby-c-farmer_1_1.jpg" alt="image"  draggable="false"/>
        <img src="http://www.fickletattoos.com/media/pixelslider/slides/arrows1_1.jpg" alt="image"  draggable="false"/>
        <img src="http://www.fickletattoos.com/media/pixelslider/slides/lost_1.jpg" alt="image"  draggable="false"/>
        <img src="http://www.fickletattoos.com/media/pixelslider/slides/sleep-in-a-grass-1a_1_1.jpg" alt="image"  draggable="false"/>
    </div>
</div>
