<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */
?>
<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>
<?php $userObj = $block->getLayout()->createBlock('Magento\Customer\Block\Account\AuthorizationLink'); ?>

<nav class="navigation" data-action="navigation">
    <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
        <?= /* @escapeNotVerified */ $_menu ?>
        <?= /* @escapeNotVerified */ $block->getChildHtml() ?>
        <?php /* ?>
        <li class="level0 nav-6 last level-top ui-menu-item" role="presentation">
        	<a href="<?= $userObj->getHref() ?>" class="level-top ui-corner-all" id="ui-id-99" tabindex="-1" role="menuitem"><span><?= $userObj->getLabel() ?></span></a>
        </li>
        */ ?>
    </ul>
</nav>
