<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/* @var \Magento\Wishlist\Block\Customer\Wishlist\Item\Options $block */
?>

<?php $options = $block->getOptionList(); ?>
<?php if ($options) : ?>
<div class="tooltip wrapper product-item-tooltip">
    <div class="tooltip content">
        <ul>
            <?php foreach ($options as $option) : ?>
                <li>
                    <dt class="label"><?= $block->escapeHtml($option['label']) ?></dt>
                    <dd class="values">
                        <?php if (is_array($option['value'])) : ?>
                            <?= /* @noEscape */ nl2br(implode("\n", $option['value'])) ?>
                        <?php else : ?>
                            <?= /* @noEscape */ $option['value'] ?>
                        <?php endif; ?>
                    </dd>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
<?php endif ?>