<div class="checkout-footer">
    <div class="container">
         <img class="logo"
             src="<?php echo $this->getViewFileUrl('images/logo.png'); ?>"
             alt="<?= __('logo') ?>">
         <ul class="links">
           <li><a href="#">Delivery Information</a></li>
           <li><a href="#">Returns Policy</a></li>
           <li><a href="#">Contact Us</a></li>
           <li><a href="#">Terms & Conditions</a></li>
         </ul>
        <ul >
           <li>
             <img class="img" src="<?php echo $this->getViewFileUrl('images/payment/visa.png'); ?>" alt="<?= __('img') ?>">
            </li>
            <li>
             <img class="img" src="<?php echo $this->getViewFileUrl('images/payment/visaelectronic.png'); ?>" alt="<?= __('img') ?>">
            </li>
            <li>
             <img class="img" src="<?php echo $this->getViewFileUrl('images/payment/paypal.png'); ?>" alt="<?= __('img') ?>">
            </li> 
            <li>
             <img class="img" src="<?php echo $this->getViewFileUrl('images/payment/master.png'); ?>" alt="<?= __('img') ?>">
            </li>
        </ul>
    </div>
</div>