<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="">
    <ul class="full-width-slider">
        <li>
        	<a href="" title="">
        		<img src="http://www.fickletattoos.com/media/pixelslider/slides/lucky-rabbitby-c-farmer_1_1.jpg" alt="image" />
        	</a>
        </li>
        <li><img src="http://www.fickletattoos.com/media/pixelslider/slides/arrows1_1.jpg" alt="image" /></li>
        <li><img src="http://www.fickletattoos.com/media/pixelslider/slides/lost_1.jpg" alt="image" /></li>
        <li><img src="http://www.fickletattoos.com/media/pixelslider/slides/sleep-in-a-grass-1a_1_1.jpg" alt="image" /></li>
    </ul>
</div>
