
<div class="blog-slider">
<ul class="blog-items">
<li>
<div class="blog-item">
<img src="http://brmbox.co.uk/brmtheme/pub/media/wysiwyg/slide-2_3.jpg">
<div class="blog-content">
<h2 class="blog-title">Pinch of Yum</h2>
<button  class="primary">
<span>READ MORE</span>
</button>
</div>
</li>

<li>
<div class="blog-item">
<img src="http://brmbox.co.uk/brmtheme/pub/media/wysiwyg/slide-2_3.jpg">
<div class="blog-content">
<h2 class="blog-title">Minimalist Baker</h2>
<button  class="primary">
<span>READ MORE</span>
</button>
</div>
</li>

<li>
<div class="blog-item">
<img src="http://brmbox.co.uk/brmtheme/pub/media/wysiwyg/slide-2_3.jpg">
<div class="blog-content">
<h2 class="blog-title">101 Cookbooks</h2>
<button  class="primary">
<span>READ MORE</span>
</button>
</div>
</li>
</ul>
</div>