<?php
/*
* @category  Theme
* @package   Bestresponse
* @author    Best Response Media Developers <dev@bestresponsemedia.co.uk>
* @copyright 2019 Best Response Media (http://bestresponsemedia.co.uk/)
* @license   Best Response Media Licence http://bestresponsemedia.co.uk/license/
* @link      http://bestresponsemedia.co.uk/
* ┌─┐┌─┐┌─┐┌┬┐ ┬─┐┌─┐┌─┐┌─┐┌─┐┌┐┬┌─┐┌─┐ ┌┐┌┐┌─┐┌─┐┬┌─┐
* │─│├┤ └─┐ │  ├┬┘├┤ └─┐├─┘│ ││││└─┐├┤  ││││├┤ │ │││─│
* └─┘└─┘└─┘ ┴  ┴└─└─┘└─┘┴  └─┘┴└┘└─┘└─┘ ┴└┘┴└─┘└─┘┴┴ ┴
*/
?>
<?php

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
/** @var \Magento\Catalog\Model\ResourceModel\Product\Collection $_productCollection */
$_productCollection = $objectManager->create('Magento\Catalog\Model\ResourceModel\Product\Collection');
/** Apply filters here */
$category_id = 4;
$_productCollection->addCategoriesFilter(['in' => [$category_id]]);
$_productCollection->addAttributeToSelect('*');
$_productCollection->load();

$_helper = $this->helper('Magento\Catalog\Helper\Output');
$viewMode = 'list';
$image = 'category_page_list';
$showDescription = true;
$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
/**
 * Position for actions regarding image size changing in vde if needed
 */
$pos = $block->getPositioned();

?>
<div class="home-products wrapper">
    <ol class="products list items product-items slick-slider">
        <?php $iterator = 1; ?>
        <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
        <?php foreach($_productCollection as $_product ): ?>
            <?= /* @escapeNotVerified */ ($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
        <div class="product-info product-item-info" data-container="product-grid">
                <?php
                $productImage = $block->getImage($_product, $image);
                if ($pos != null) {
                    $position = ' style="left:' . $productImage->getWidth() . 'px;'
                        . 'top:' . $productImage->getHeight() . 'px;"';
                }
                ?>
                <?php // Product Image ?>
                <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="product-photo product-item-photo" tabindex="-1">
                    <?= $productImage->toHtml() ?>
                </a>
                <div class="product-details product-item-details">
                    <?php
                    $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                    ?>
                    <span class="product-name product-item-name">
                            <a class="product-item-link"
                               href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>">
                                <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                            </a>
                        </span>
                    <?php /* ?>
                        <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                        <?php */ ?>
                    <?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?>
                    <?= $block->getProductDetailsHtml($_product) ?>
                    <?php /* ?>

                        <div class="product-item-inner">
                            <div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
                                <div data-role="add-to-links" class="add-to-wishlist actions-secondary"<?= strpos($pos, $viewMode . '-secondary') ? $position : '' ?>>
                                    <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                        <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                        */ ?>
                </div>
        </div>
        <?= ($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
    <?php endforeach; ?>
    </ol>
</div>