<?php
/*
* @category  Theme
* @package   Bestresponse
* @author    Best Response Media Developers <dev@bestresponsemedia.co.uk>
* @copyright 2019 Best Response Media (http://bestresponsemedia.co.uk/)
* @license   Best Response Media Licence http://bestresponsemedia.co.uk/license/
* @link      http://bestresponsemedia.co.uk/
* ┌─┐┌─┐┌─┐┌┬┐ ┬─┐┌─┐┌─┐┌─┐┌─┐┌┐┬┌─┐┌─┐ ┌┐┌┐┌─┐┌─┐┬┌─┐
* │─│├┤ └─┐ │  ├┬┘├┤ └─┐├─┘│ ││││└─┐├┤  ││││├┤ │ │││─│
* └─┘└─┘└─┘ ┴  ┴└─└─┘└─┘┴  └─┘┴└┘└─┘└─┘ ┴└┘┴└─┘└─┘┴┴ ┴
*/
?>
<div class="footer-newsletter">
  <div class="newsletter-container">
        <span class="title"><?= $block->escapeHtml(__('Join our newsletter and get 10% off!')) ?></span>
        <span class="sub-title"><?= $block->escapeHtml(__('Sign up to our newsletter to receive offers and the latest news, plus enjoy 10% off your next purchase. You can opt out at any time. ')) ?></span>
        
        <form 
          class="subscribe-form"
          novalidate
          action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
          method="post"
          data-mage-init='{"validation": {"errorClass": "mage-error"}}'
          id="newsletter-validate-detail">
               
          <div class="newsletter-field icon-newsletter">
            <label class="label" for="newsletter"><span><?= $block->escapeHtml(__('Sign Up for Our Newsletter:')) ?></span></label>
            <div class="control">
              <input name="email" type="email" id="newsletter"
                placeholder="<?= $block->escapeHtmlAttr(__('Enter your email address')) ?>"
                data-validate="{required:true, 'validate-email':true}" />
            </div>
            <div class="actions">
              <button class="action subscribe primary" title="<?= $block->escapeHtmlAttr(__('Subscribe')) ?>" type="submit">
                <span><?= $block->escapeHtml(__('Sign up')) ?></span>
              </button>
            </div>
          </div>
          
        </form>
        
        <div class="declaration">
            To find more about how we use your data. read our
            <a href="#" title="privacy policy">privacy policy</a>.
        </div>
  </div>
</div>